### YamlMime:ManagedReference
items:
- uid: AetherUtils.Core.Security
  commentId: N:AetherUtils.Core.Security
  id: AetherUtils.Core.Security
  children:
  - AetherUtils.Core.Security.SecretQa
  langs:
  - csharp
  - vb
  name: AetherUtils.Core.Security
  nameWithType: AetherUtils.Core.Security
  fullName: AetherUtils.Core.Security
  type: Namespace
  assemblies:
  - AetherUtils.Core
references:
- uid: AetherUtils.Core.Security.SecretQa
  commentId: T:AetherUtils.Core.Security.SecretQa
  href: AetherUtils.Core.Security.SecretQa.html
  name: SecretQa
  nameWithType: SecretQa
  fullName: AetherUtils.Core.Security.SecretQa
shouldSkipMarkup: true
